import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(process.cwd(), ".env") });

export default {
	node_env: process.env.NODE_ENV,
	port: process.env.PORT,
	database_url: process.env.DATABASE_URL,
	backend_url: process.env.BACKEND_URL,
	frontend_url: process.env.FRONTEND_URL,
	bcrypt_salt_rounds: process.env.BCRYPT_SALT_ROUNDS,
	jwt_access_secret: process.env.JWT_ACCESS_SECRET!,
	jwt_refresh_secret: process.env.JWT_REFRESH_SECRET!,
	jwt_access_expires_in: process.env.JWT_ACCESS_EXPIRES_IN!,
	jwt_refresh_expires_in: process.env.JWT_REFRESH_EXPIRES_IN!,
	google_client_id: process.env.GOOGLE_CLIENT_ID!,
	google_client_secret: process.env.GOOGLE_CLIENT_SECRET!,
	super_admin_name: process.env.SUPER_ADMIN_NAME!,
	super_admin_email: process.env.SUPER_ADMIN_EMAIL!,
	super_admin_password: process.env.SUPER_ADMIN_PASSWORD!,
	tester_admin_name: process.env.TESTER_ADMIN_NAME!,
	tester_admin_email: process.env.TESTER_ADMIN_EMAIL!,
	tester_admin_password: process.env.TESTER_ADMIN_PASSWORD!,
	tester_owner_name: process.env.TESTER_OWNER_NAME!,
	tester_owner_email: process.env.TESTER_OWNER_EMAIL!,
	tester_owner_password: process.env.TESTER_OWNER_PASSWORD!,
	tester_manager_name: process.env.TESTER_MANAGER_NAME!,
	tester_manager_email: process.env.TESTER_MANAGER_EMAIL!,
	tester_manager_password: process.env.TESTER_MANAGER_PASSWORD!,
	tester_tenant_name: process.env.TESTER_TENANT_NAME!,
	tester_tenant_email: process.env.TESTER_TENANT_EMAIL!,
	tester_tenant_password: process.env.TESTER_TENANT_PASSWORD!,
	redis_user: process.env.REDIS_USER!,
	redis_password: process.env.REDIS_PASSWORD!,
	redis_host: process.env.REDIS_HOST!,
	redis_port: process.env.REDIS_PORT!,
	smtp_user: process.env.SMTP_USER!,
	email_sender: process.env.EMAIL_SENDER!,
	smtp_password: process.env.SMTP_PASSWORD!,
	cloudinary_cloud_name: process.env.CLOUDINARY_CLOUD_NAME!,
	cloudinary_api_key: process.env.CLOUDINARY_API_KEY!,
	cloudinary_api_secret: process.env.CLOUDINARY_API_SECRET!,
	bkash_base_url: process.env.BKASH_BASE_URL!,
	bkash_username: process.env.BKASH_USERNAME!,
	bkash_password: process.env.BKASH_PASSWORD!,
	bkash_app_key: process.env.BKASH_APP_KEY!,
	bkash_app_secret: process.env.BKASH_APP_SECRET!,
	bkash_callback_url: process.env.BKASH_CALLBACK_URL!,
	ssl_commerz_store_id: process.env.SSL_COMMERZ_STORE_ID!,
	ssl_commerz_store_passwd: process.env.SSL_COMMERZ_STORE_PASSWORD!,
	sslcommerz_init_url: process.env.SSLCOMMERZ_INIT_URL!,
	sslcommerz_validate_url: process.env.SSLCOMMERZ_VALIDATE_URL!,
	stripe_secret_key: process.env.STRIPE_SECRET_KEY!,
	stripe_webhook_secret: process.env.STRIPE_WEBHOOK_SECRET!,
	stripe_currency: process.env.STRIPE_CURRENCY || "usd",
	stripe_bdt_to_base: process.env.STRIPE_BDT_TO_BASE || "120",
	backend_public_url: process.env.BACKEND_PUBLIC_URL || process.env.BACKEND_URL!,
};
