import cron from "node-cron";
import { addMonths, startOfDay } from "date-fns";
import {
	ApplicationStatus,
	InvoiceType,
	LeaseStatus,
} from "../../generated/prisma/enums";
import { prisma } from "./prisma";
import { recalculateRoomStatus } from "../utils/roomStatus";

// Applications that stay PENDING for longer than 14 days are auto-expired so
// the owner does not have to clean them up manually.
export const expirePendingApplications = async () => {
	const cutoff = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000);

	const result = await prisma.application.updateMany({
		where: {
			status: ApplicationStatus.PENDING,
			isDeleted: false,
			createdAt: { lt: cutoff },
		},
		data: { status: ApplicationStatus.EXPIRED },
	});

	if (result.count > 0) {
		console.log(`Cron: expired ${result.count} stale pending application(s).`);
	}
};

// Runs daily: creates any RENT invoices that are due but not yet generated for
// active leases (it also catches up automatically when the server was offline).
// The booking deposit covers the first month, so rent invoices start from the
// second month of the lease.
export const generateMonthlyRentInvoices = async () => {
	const today = startOfDay(new Date()).getTime();

	const activeLeases = await prisma.lease.findMany({
		where: { status: LeaseStatus.ACTIVE, isDeleted: false },
	});

	let created = 0;

	for (const lease of activeLeases) {
		// first payable month = lease start + 1 month (deposit covers month one)
		let periodStart = addMonths(startOfDay(lease.startDate), 1);
		const leaseEnd = startOfDay(lease.endDate).getTime();

		// walk month by month while the whole period still sits inside the lease
		while (periodStart.getTime() < leaseEnd) {
			// future periods will be generated by a later run of this job
			if (periodStart.getTime() > today) {
				break;
			}

			const existing = await prisma.invoice.findFirst({
				where: {
					leaseId: lease.id,
					type: InvoiceType.RENT,
					periodStart,
				},
			});

			if (!existing) {
				const periodEnd = addMonths(periodStart, 1);

				await prisma.invoice.create({
					data: {
						type: InvoiceType.RENT,
						amount: lease.monthlyRent,
						periodStart,
						periodEnd,
						dueDate: periodStart,
						leaseId: lease.id,
						roomId: lease.roomId,
						description: `Monthly rent for ${periodStart.toLocaleDateString()} - ${periodEnd.toLocaleDateString()}`,
					},
				});
				created += 1;
			}

			periodStart = addMonths(periodStart, 1);
		}
	}

	if (created > 0) {
		console.log(`Cron: generated ${created} monthly rent invoice(s).`);
	}
};

// Runs daily: leases whose end date has passed become COMPLETED automatically
// and their occupied bed is released back to the room.
export const finalizeExpiredLeases = async () => {
	const today = startOfDay(new Date());

	const expiredLeases = await prisma.lease.findMany({
		where: {
			status: LeaseStatus.ACTIVE,
			isDeleted: false,
			endDate: { lt: today },
		},
	});

	for (const lease of expiredLeases) {
		const transactionResult = await prisma.$transaction(async (tx) => {
			const room = await tx.room.findUnique({
				where: { id: lease.roomId },
			});

			const updatedLease = await tx.lease.update({
				where: { id: lease.id },
				data: { status: LeaseStatus.COMPLETED },
			});

			// release the occupied bed, if the room still counts it
			if (room && room.occupiedBeds > 0) {
				await tx.room.update({
					where: { id: room.id },
					data: { occupiedBeds: { decrement: 1 } },
				});

				await recalculateRoomStatus(room.id, tx);
			}

			return updatedLease;
		});

		console.log(
			`Cron: lease ${transactionResult.id} completed (end date passed).`,
		);
	}
};

// Register every recurring background job (invoked once on server boot).
export const scheduleBackgroundJobs = () => {
	// generate monthly rent invoices every day at 00:10
	cron.schedule("10 0 * * *", async () => {
		try {
			await generateMonthlyRentInvoices();
		} catch (error) {
			console.log("Cron: Failed to generate monthly rent invoices", error);
		}
	});

	// finalize expired leases every day at 00:15
	cron.schedule("15 0 * * *", async () => {
		try {
			await finalizeExpiredLeases();
		} catch (error) {
			console.log("Cron: Failed to finalize expired leases", error);
		}
	});

	// expire stale pending applications every day at 00:20
	cron.schedule("20 0 * * *", async () => {
		try {
			await expirePendingApplications();
		} catch (error) {
			console.log("Cron: Failed to expire pending applications", error);
		}
	});

	console.log(
		"Background jobs scheduled (rent invoices, lease finalizer, application expiry).",
	);
};
