import cron from "node-cron";
import { addMonths, startOfDay } from "date-fns";
import {
	ApplicationStatus,
	InvoiceStatus,
	InvoiceType,
	LeaseStatus,
	MembershipStatus,
	NotificationType,
	PaymentGateway,
	PaymentStatus,
} from "../../generated/prisma/enums";
import config from "../config";
import { prisma } from "./prisma";
import { getStripe } from "./stripe";
import { writeAuditLog } from "../utils/audit";
import { createNotification } from "../utils/notification";
import { recalculateRoomStatus } from "../utils/roomStatus";

// Applications that stay PENDING for longer than 14 days are auto-expired so
// the owner does not have to clean them up manually.
export const expirePendingApplications = async () => {
	const cutoff = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000);

	const staleApplications = await prisma.application.findMany({
		where: {
			status: ApplicationStatus.PENDING,
			isDeleted: false,
			createdAt: { lt: cutoff },
		},
		select: { id: true },
	});

	if (staleApplications.length === 0) {
		return;
	}

	await prisma.$transaction(async (tx) => {
		for (const application of staleApplications) {
			await tx.application.update({
				where: { id: application.id },
				data: { status: ApplicationStatus.EXPIRED },
			});

			await writeAuditLog(
				{
					action: "APPLICATION_EXPIRED",
					entity: "Application",
					entityId: application.id,
					actorRole: "SYSTEM",
					before: { status: ApplicationStatus.PENDING },
					after: { status: ApplicationStatus.EXPIRED },
				},
				tx,
			);
		}
	});

	console.log(
		`Cron: expired ${staleApplications.length} stale pending application(s).`,
	);
};

// Runs daily: creates any RENT invoices that are due but not yet generated for
// active leases (it also catches up automatically when the server was offline).
// The booking deposit covers the first month, so rent invoices start from the
// second month of the lease.
export const generateMonthlyRentInvoices = async () => {
	const today = startOfDay(new Date()).getTime();

	const activeLeases = await prisma.lease.findMany({
		where: { status: LeaseStatus.ACTIVE, isDeleted: false },
	});

	let created = 0;

	for (const lease of activeLeases) {
		// first payable month = lease start + 1 month (deposit covers month one)
		let periodStart = addMonths(startOfDay(lease.startDate), 1);
		const leaseEnd = startOfDay(lease.endDate).getTime();

		// walk month by month while the whole period still sits inside the lease
		while (periodStart.getTime() < leaseEnd) {
			// future periods will be generated by a later run of this job
			if (periodStart.getTime() > today) {
				break;
			}

			const existing = await prisma.invoice.findFirst({
				where: {
					leaseId: lease.id,
					type: InvoiceType.RENT,
					periodStart,
				},
			});

			if (!existing) {
				const periodEnd = addMonths(periodStart, 1);

				await prisma.invoice.create({
					data: {
						type: InvoiceType.RENT,
						amount: lease.monthlyRent,
						periodStart,
						periodEnd,
						dueDate: periodStart,
						leaseId: lease.id,
						roomId: lease.roomId,
						description: `Monthly rent for ${periodStart.toLocaleDateString()} - ${periodEnd.toLocaleDateString()}`,
					},
				});
				created += 1;
			}

			periodStart = addMonths(periodStart, 1);
		}
	}

	if (created > 0) {
		console.log(`Cron: generated ${created} monthly rent invoice(s).`);
	}
};

// Runs daily: leases whose end date has passed become COMPLETED automatically
// and their occupied bed is released back to the room.
export const finalizeExpiredLeases = async () => {
	const today = startOfDay(new Date());

	const expiredLeases = await prisma.lease.findMany({
		where: {
			status: LeaseStatus.ACTIVE,
			isDeleted: false,
			endDate: { lt: today },
		},
	});

	for (const lease of expiredLeases) {
		const transactionResult = await prisma.$transaction(async (tx) => {
			const room = await tx.room.findUnique({
				where: { id: lease.roomId },
			});

			const updatedLease = await tx.lease.update({
				where: { id: lease.id },
				data: { status: LeaseStatus.COMPLETED },
			});

			// audit trail of the automatic completion (system actor)
			await writeAuditLog(
				{
					action: "LEASE_COMPLETED",
					entity: "Lease",
					entityId: lease.id,
					actorRole: "SYSTEM",
					before: { status: LeaseStatus.ACTIVE },
					after: { status: LeaseStatus.COMPLETED },
				},
				tx,
			);

			// P3: close live roommate memberships with the lease — same
			// transaction, so no member is ever orphaned by a completion
			const liveMemberships = await tx.roommateMembership.findMany({
				where: {
					leaseId: lease.id,
					status: { in: [MembershipStatus.PENDING, MembershipStatus.ACTIVE] },
				},
				select: {
					id: true,
					status: true,
					tenantProfile: { select: { userId: true } },
				},
			});

			if (liveMemberships.length > 0) {
				await tx.roommateMembership.updateMany({
					where: {
						leaseId: lease.id,
						status: { in: [MembershipStatus.PENDING, MembershipStatus.ACTIVE] },
					},
					data: {
						status: MembershipStatus.REMOVED,
						removedAt: new Date(),
						removedBy: "system-cron",
						removalReason: "Lease completed",
					},
				});

				for (const membership of liveMemberships) {
					await writeAuditLog(
						{
							action: "MEMBERSHIP_REMOVED",
							entity: "RoommateMembership",
							entityId: membership.id,
							actorRole: "SYSTEM",
							before: { status: membership.status },
							after: {
								status: MembershipStatus.REMOVED,
								reason: "Lease completed",
							},
						},
						tx,
					);
				}
			}

			// release the occupied bed, if the room still counts it
			if (room && room.occupiedBeds > 0) {
				await tx.room.update({
					where: { id: room.id },
					data: { occupiedBeds: { decrement: 1 } },
				});

				await recalculateRoomStatus(room.id, tx);
			}

			return {
				lease: updatedLease,
				memberUserIds: liveMemberships.map((m) => m.tenantProfile.userId),
			};
		});

		// members lose their arrangement with the completed lease (fail-soft,
		// never retried — the closure itself is already committed)
		for (const memberUserId of transactionResult.memberUserIds) {
			try {
				await createNotification({
					userId: memberUserId,
					type: NotificationType.ROOMMATE,
					title: "Roommate membership ended 🚪",
					message:
						"The lease for your room has ended, so your roommate membership has ended.",
					data: { leaseId: lease.id },
				});
			} catch (error) {
				console.log("Cron: member notification failed:", error);
			}
		}

		console.log(
			`Cron: lease ${transactionResult.lease.id} completed (end date passed).`,
		);
	}
};

// Runs daily: payments still PROCESSING after 24h had their final provider
// notification lost. The cron NEVER auto-settles (I-G5): a definitive
// failed/expired verdict downgrades the row (conditional write, I-G4) so the
// tenant can retry; a "paid" or ambiguous verdict is flagged into the admin
// settle queue via a PAYMENT_STALE_FLAGGED audit (the success-side mirror
// of REFUND_PENDING reconciliation).
export const reconcileStaleProcessingPayments = async () => {
	const cutoff = new Date(Date.now() - 24 * 60 * 60 * 1000);

	const stalePayments = await prisma.payment.findMany({
		where: {
			status: PaymentStatus.PROCESSING,
			updatedAt: { lt: cutoff },
		},
	});

	if (stalePayments.length === 0) {
		return;
	}

	for (const payment of stalePayments) {
		try {
			// probe the provider for the definitive state
			let verdict: "paid" | "failed" | "expired" | "ambiguous";

			if (payment.gateway === PaymentGateway.STRIPE) {
				const session = await getStripe().checkout.sessions.retrieve(
					payment.bKashPaymentId as string,
				);

				if (
					session.payment_status === "paid" ||
					session.payment_status === "no_payment_required"
				) {
					verdict = "paid";
				} else if (session.status === "expired") {
					verdict = "expired";
				} else if (session.status === "complete") {
					verdict = "paid";
				} else {
					verdict = "ambiguous";
				}
			} else if (payment.gateway === PaymentGateway.BKASH) {
				// re-executing a completed session is an idempotent status
				// probe; an ERRORED probe is ambiguous (a transient gateway
				// fault must never wrongly downgrade a row)
				try {
					const { executeBkashPayment } = await import("./bKash");
					const executed = await executeBkashPayment(
						payment.bKashPaymentId as string,
					);

					verdict =
						executed.transactionStatus === "Completed" ? "paid" : "failed";
				} catch (error) {
					console.log(
						`Cron: bKash re-execute probe errored for ${payment.id}:`,
						error,
					);
					verdict = "ambiguous";
				}
			} else if (payment.gateway === PaymentGateway.SSLCOMMERZ) {
				// re-validate against the validator using the val_id stored
				// from the original confirmation attempt (if any)
				const raw = payment.gatwayResponse as { val_id?: string } | null;

				if (raw?.val_id) {
					const response = await fetch(
						`${config.sslcommerz_validate_url}?val_id=${encodeURIComponent(raw.val_id)}&store_id=${config.ssl_commerz_store_id}&store_passwd=${config.ssl_commerz_store_passwd}&format=json`,
					);
					const data = (await response.json()) as { status?: string };

					verdict =
						data.status === "VALID" || data.status === "VALIDATED"
							? "paid"
							: "failed";
				} else {
					// no val_id ever arrived: nothing to validate against
					verdict = "ambiguous";
				}
			} else {
				verdict = "ambiguous";
			}

			if (verdict === "failed" || verdict === "expired") {
				// conditional downgrade: the tenant can retry immediately
				await prisma.$transaction(async (tx) => {
					const result = await tx.payment.updateMany({
						where: {
							id: payment.id,
							status: PaymentStatus.PROCESSING,
						},
						data: {
							status:
								verdict === "failed"
									? PaymentStatus.FAILED
									: PaymentStatus.CANCELLED,
						},
					});

					if (result.count === 0) {
						return;
					}

					if (payment.invoiceId) {
						await tx.invoice.update({
							where: { id: payment.invoiceId },
							data: {
								status:
									verdict === "failed"
										? InvoiceStatus.FAILED
										: InvoiceStatus.UNPAID,
							},
						});
					}

					await writeAuditLog(
						{
							action: "PAYMENT_STALE_RECONCILED",
							entity: "Payment",
							entityId: payment.id,
							actorRole: "SYSTEM",
							before: { status: PaymentStatus.PROCESSING },
							after: {
								status:
									verdict === "failed"
										? PaymentStatus.FAILED
										: PaymentStatus.CANCELLED,
								gateway: payment.gateway,
							},
						},
						tx,
					);
				});

				console.log(
					`Cron: stale payment ${payment.id} downgraded (${verdict}).`,
				);
			} else {
				// paid / ambiguous: flag for the admin settle queue
				await writeAuditLog({
					action: "PAYMENT_STALE_FLAGGED",
					entity: "Payment",
					entityId: payment.id,
					actorRole: "SYSTEM",
					before: { status: PaymentStatus.PROCESSING },
					after: {
						providerVerdict: verdict,
						gateway: payment.gateway,
						resolution: "admin settle queue",
					},
				});

				console.log(
					`Cron: stale payment ${payment.id} flagged (${verdict}) for the admin settle queue.`,
				);
			}
		} catch (error) {
			// one bad row must never block the rest of the batch
			console.log(`Cron: stale payment probe failed for ${payment.id}:`, error);
		}
	}
};

// Register every recurring background job (invoked once on server boot).
export const scheduleBackgroundJobs = () => {
	// generate monthly rent invoices every day at 00:10
	cron.schedule("10 0 * * *", async () => {
		try {
			await generateMonthlyRentInvoices();
		} catch (error) {
			console.log("Cron: Failed to generate monthly rent invoices", error);
		}
	});

	// finalize expired leases every day at 00:15
	cron.schedule("15 0 * * *", async () => {
		try {
			await finalizeExpiredLeases();
		} catch (error) {
			console.log("Cron: Failed to finalize expired leases", error);
		}
	});

	// expire stale pending applications every day at 00:20
	cron.schedule("20 0 * * *", async () => {
		try {
			await expirePendingApplications();
		} catch (error) {
			console.log("Cron: Failed to expire pending applications", error);
		}
	});

	// reconcile stale payment sessions every day at 00:25
	cron.schedule("25 0 * * *", async () => {
		try {
			await reconcileStaleProcessingPayments();
		} catch (error) {
			console.log("Cron: Failed to reconcile stale payment sessions", error);
		}
	});

	console.log(
		"Background jobs scheduled (rent invoices, lease finalizer, application expiry, payment reconciliation).",
	);
};
