import cron from "node-cron";
import { addMonths, startOfDay } from "date-fns";
import {
	ApplicationStatus,
	InvoiceType,
	LeaseStatus,
	MembershipStatus,
	NotificationType,
} from "../../generated/prisma/enums";
import { prisma } from "./prisma";
import { writeAuditLog } from "../utils/audit";
import { createNotification } from "../utils/notification";
import { recalculateRoomStatus } from "../utils/roomStatus";

// Applications that stay PENDING for longer than 14 days are auto-expired so
// the owner does not have to clean them up manually.
export const expirePendingApplications = async () => {
	const cutoff = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000);

	const staleApplications = await prisma.application.findMany({
		where: {
			status: ApplicationStatus.PENDING,
			isDeleted: false,
			createdAt: { lt: cutoff },
		},
		select: { id: true },
	});

	if (staleApplications.length === 0) {
		return;
	}

	await prisma.$transaction(async (tx) => {
		for (const application of staleApplications) {
			await tx.application.update({
				where: { id: application.id },
				data: { status: ApplicationStatus.EXPIRED },
			});

			await writeAuditLog(
				{
					action: "APPLICATION_EXPIRED",
					entity: "Application",
					entityId: application.id,
					actorRole: "SYSTEM",
					before: { status: ApplicationStatus.PENDING },
					after: { status: ApplicationStatus.EXPIRED },
				},
				tx,
			);
		}
	});

	console.log(
		`Cron: expired ${staleApplications.length} stale pending application(s).`,
	);
};

// Runs daily: creates any RENT invoices that are due but not yet generated for
// active leases (it also catches up automatically when the server was offline).
// The booking deposit covers the first month, so rent invoices start from the
// second month of the lease.
export const generateMonthlyRentInvoices = async () => {
	const today = startOfDay(new Date()).getTime();

	const activeLeases = await prisma.lease.findMany({
		where: { status: LeaseStatus.ACTIVE, isDeleted: false },
	});

	let created = 0;

	for (const lease of activeLeases) {
		// first payable month = lease start + 1 month (deposit covers month one)
		let periodStart = addMonths(startOfDay(lease.startDate), 1);
		const leaseEnd = startOfDay(lease.endDate).getTime();

		// walk month by month while the whole period still sits inside the lease
		while (periodStart.getTime() < leaseEnd) {
			// future periods will be generated by a later run of this job
			if (periodStart.getTime() > today) {
				break;
			}

			const existing = await prisma.invoice.findFirst({
				where: {
					leaseId: lease.id,
					type: InvoiceType.RENT,
					periodStart,
				},
			});

			if (!existing) {
				const periodEnd = addMonths(periodStart, 1);

				await prisma.invoice.create({
					data: {
						type: InvoiceType.RENT,
						amount: lease.monthlyRent,
						periodStart,
						periodEnd,
						dueDate: periodStart,
						leaseId: lease.id,
						roomId: lease.roomId,
						description: `Monthly rent for ${periodStart.toLocaleDateString()} - ${periodEnd.toLocaleDateString()}`,
					},
				});
				created += 1;
			}

			periodStart = addMonths(periodStart, 1);
		}
	}

	if (created > 0) {
		console.log(`Cron: generated ${created} monthly rent invoice(s).`);
	}
};

// Runs daily: leases whose end date has passed become COMPLETED automatically
// and their occupied bed is released back to the room.
export const finalizeExpiredLeases = async () => {
	const today = startOfDay(new Date());

	const expiredLeases = await prisma.lease.findMany({
		where: {
			status: LeaseStatus.ACTIVE,
			isDeleted: false,
			endDate: { lt: today },
		},
	});

	for (const lease of expiredLeases) {
		const transactionResult = await prisma.$transaction(async (tx) => {
			const room = await tx.room.findUnique({
				where: { id: lease.roomId },
			});

			const updatedLease = await tx.lease.update({
				where: { id: lease.id },
				data: { status: LeaseStatus.COMPLETED },
			});

			// audit trail of the automatic completion (system actor)
			await writeAuditLog(
				{
					action: "LEASE_COMPLETED",
					entity: "Lease",
					entityId: lease.id,
					actorRole: "SYSTEM",
					before: { status: LeaseStatus.ACTIVE },
					after: { status: LeaseStatus.COMPLETED },
				},
				tx,
			);

			// P3: close live roommate memberships with the lease — same
			// transaction, so no member is ever orphaned by a completion
			const liveMemberships = await tx.roommateMembership.findMany({
				where: {
					leaseId: lease.id,
					status: { in: [MembershipStatus.PENDING, MembershipStatus.ACTIVE] },
				},
				select: {
					id: true,
					status: true,
					tenantProfile: { select: { userId: true } },
				},
			});

			if (liveMemberships.length > 0) {
				await tx.roommateMembership.updateMany({
					where: {
						leaseId: lease.id,
						status: { in: [MembershipStatus.PENDING, MembershipStatus.ACTIVE] },
					},
					data: {
						status: MembershipStatus.REMOVED,
						removedAt: new Date(),
						removedBy: "system-cron",
						removalReason: "Lease completed",
					},
				});

				for (const membership of liveMemberships) {
					await writeAuditLog(
						{
							action: "MEMBERSHIP_REMOVED",
							entity: "RoommateMembership",
							entityId: membership.id,
							actorRole: "SYSTEM",
							before: { status: membership.status },
							after: {
								status: MembershipStatus.REMOVED,
								reason: "Lease completed",
							},
						},
						tx,
					);
				}
			}

			// release the occupied bed, if the room still counts it
			if (room && room.occupiedBeds > 0) {
				await tx.room.update({
					where: { id: room.id },
					data: { occupiedBeds: { decrement: 1 } },
				});

				await recalculateRoomStatus(room.id, tx);
			}

			return {
				lease: updatedLease,
				memberUserIds: liveMemberships.map((m) => m.tenantProfile.userId),
			};
		});

		// members lose their arrangement with the completed lease (fail-soft,
		// never retried — the closure itself is already committed)
		for (const memberUserId of transactionResult.memberUserIds) {
			try {
				await createNotification({
					userId: memberUserId,
					type: NotificationType.ROOMMATE,
					title: "Roommate membership ended 🚪",
					message:
						"The lease for your room has ended, so your roommate membership has ended.",
					data: { leaseId: lease.id },
				});
			} catch (error) {
				console.log("Cron: member notification failed:", error);
			}
		}

		console.log(
			`Cron: lease ${transactionResult.lease.id} completed (end date passed).`,
		);
	}
};

// Register every recurring background job (invoked once on server boot).
export const scheduleBackgroundJobs = () => {
	// generate monthly rent invoices every day at 00:10
	cron.schedule("10 0 * * *", async () => {
		try {
			await generateMonthlyRentInvoices();
		} catch (error) {
			console.log("Cron: Failed to generate monthly rent invoices", error);
		}
	});

	// finalize expired leases every day at 00:15
	cron.schedule("15 0 * * *", async () => {
		try {
			await finalizeExpiredLeases();
		} catch (error) {
			console.log("Cron: Failed to finalize expired leases", error);
		}
	});

	// expire stale pending applications every day at 00:20
	cron.schedule("20 0 * * *", async () => {
		try {
			await expirePendingApplications();
		} catch (error) {
			console.log("Cron: Failed to expire pending applications", error);
		}
	});

	console.log(
		"Background jobs scheduled (rent invoices, lease finalizer, application expiry).",
	);
};
